function FABridge(a,b){this.target=a;this.remoteTypeCache={};this.remoteInstanceCache={};this.remoteFunctionCache={};this.localFunctionCache={};this.bridgeID=FABridge.nextBridgeID++;this.name=b;this.nextLocalFuncID=0;FABridge.instances[this.name]=this;FABridge.idMap[this.bridgeID]=this;return this}FABridge.TYPE_ASINSTANCE=1;FABridge.TYPE_ASFUNCTION=2;FABridge.TYPE_JSFUNCTION=3;FABridge.TYPE_ANONYMOUS=4;FABridge.initCallbacks={};FABridge.userTypes={};
FABridge.addToUserTypes=function(){for(var a=0;a<arguments.length;a++)FABridge.userTypes[arguments[a]]={typeName:arguments[a],enriched:!1}};FABridge.argsToArray=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b};FABridge.isArray=function(a){return!!a&&(a instanceof Array||"[object Array]"===Object.prototype.toString.call(a))};FABridge.isASProxy=function(a){return!!a&&(a instanceof ASProxy||!!a.bridgeName&&!!a.typeName&&"ASProxy"===a.className)};
function instanceFactory(a){this.fb_instance_id=a;return this}function FABridge__invokeJSFunction(a){var b=a[0];a=a.concat();a.shift();return FABridge.extractBridgeFromID(b).invokeLocalFunction(b,a)}FABridge.addInitializationCallback=function(a,b){var c=FABridge.instances[a];void 0!=c?b.call(c):(c=FABridge.initCallbacks[a],null==c&&(FABridge.initCallbacks[a]=c=[]),c.push(b))};
function FABridge__bridgeInitialized(a){var b=document.getElementsByTagName("object"),c=b.length,e=[];if(0<c)for(var d=0;d<c;d++)"undefined"!=typeof b[d].SetVariable&&(e[e.length]=b[d]);c=document.getElementsByTagName("embed");d=c.length;b=[];if(0<d)for(var g=0;g<d;g++)"undefined"!=typeof c[g].SetVariable&&(b[b.length]=c[g]);g=e.length;c=b.length;d="bridgeName="+a;if(1==g&&!c||1==g&&1==c)FABridge.attachBridge(e[0],a);else if(1==c&&!g)FABridge.attachBridge(b[0],a);else{var n=!1;if(1<g)for(var f=0;f<
g;f++){for(var u=e[f].childNodes,s=0;s<u.length;s++){var l=u[s];if(1==l.nodeType&&"param"==l.tagName.toLowerCase()&&"flashvars"==l.name.toLowerCase()&&0<=l.value.indexOf(d)){FABridge.attachBridge(e[f],a);n=!0;break}}if(n)break}if(!n&&1<c)for(e=0;e<c;e++)if(0<=b[e].attributes.getNamedItem("flashVars").nodeValue.indexOf(d)){FABridge.attachBridge(b[e],a);break}}return!0}FABridge.nextBridgeID=0;FABridge.instances={};FABridge.idMap={};FABridge.refCount=0;
FABridge.extractBridgeFromID=function(a){return FABridge.idMap[a>>16]};FABridge.attachBridge=function(a,b){var c=new FABridge(a,b);FABridge[b]=c;var e=FABridge.initCallbacks[b];if(null!=e){for(var d=0;d<e.length;d++)e[d].call(c);delete FABridge.initCallbacks[b]}};FABridge.blockedMethods={toString:!0,get:!0,set:!0,call:!0};
FABridge.prototype={root:function(){return this.deserialize(this.target.getRoot())},releaseASObjects:function(){return this.target.releaseASObjects()},releaseNamedASObject:function(a){return"object"!=typeof a?!1:this.target.releaseNamedASObject(a.fb_instance_id)},create:function(a){return this.deserialize(this.target.create(a))},makeID:function(a){return(this.bridgeID<<16)+a},getPropertyFromAS:function(a,b){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
FABridge.refCount++;retVal=this.target.getPropFromAS(a,b);retVal=this.handleError(retVal);FABridge.refCount--;return retVal},setPropertyInAS:function(a,b,c){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");FABridge.refCount++;retVal=this.target.setPropInAS(a,b,this.serialize(c));retVal=this.handleError(retVal);FABridge.refCount--;return retVal},callASFunction:function(a,
b){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");FABridge.refCount++;retVal=this.target.invokeASFunction(a,this.serialize(b));retVal=this.handleError(retVal);FABridge.refCount--;return retVal},callASMethod:function(a,b,c){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
FABridge.refCount++;c=this.encodeJSON(this.serialize(c));retVal=this.target.invokeASMethod(a,b,c);retVal=this.handleError(retVal);FABridge.refCount--;return retVal},invokeLocalFunction:function(a,b){var c,e=this.localFunctionCache[a];void 0!=e&&(c=this.serialize(e.apply(null,this.deserialize(b))));return c},getTypeFromName:function(a){return this.remoteTypeCache[a]},createProxy:function(a,b){var c=this.getTypeFromName(b);instanceFactory.prototype=c;c=new instanceFactory(a);return this.remoteInstanceCache[a]=
c},getProxy:function(a){return this.remoteInstanceCache[a]},addTypeDataToCache:function(a){newType=new ASProxy(this,a.name);for(var b=a.accessors,c=0;c<b.length;c++)this.addPropertyToType(newType,b[c]);a=a.methods;for(c=0;c<a.length;c++)void 0==FABridge.blockedMethods[a[c]]&&this.addMethodToType(newType,a[c]);return this.remoteTypeCache[newType.typeName]=newType},addPropertyToType:function(a,b){var c=b.charAt(0),e;"a"<=c&&"z">=c?(e="get"+c.toUpperCase()+b.substr(1),c="set"+c.toUpperCase()+b.substr(1)):
(e="get"+b,c="set"+b);a[c]=function(a){this.bridge.setPropertyInAS(this.fb_instance_id,b,a)};a[e]=function(){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,b))}},addMethodToType:function(a,b){a[b]=function(){return this.bridge.deserialize(this.bridge.callASMethod(this.fb_instance_id,b,FABridge.argsToArray(arguments)))}},getFunctionProxy:function(a){var b=this;null==this.remoteFunctionCache[a]&&(this.remoteFunctionCache[a]=function(){b.callASFunction(a,FABridge.argsToArray(arguments))});
return this.remoteFunctionCache[a]},getFunctionID:function(a){void 0==a.__bridge_id__&&(a.__bridge_id__=this.makeID(this.nextLocalFuncID++),this.localFunctionCache[a.__bridge_id__]=a);return a.__bridge_id__},serialize:function(a){var b={},c=typeof a;if("number"==c||"string"==c||"boolean"==c||null==c||"undefined"==c)b=a;else if(FABridge.isArray(a)){b=[];for(c=0;c<a.length;c++)b[c]=this.serialize(a[c])}else"function"==c?(b.type=FABridge.TYPE_JSFUNCTION,b.value=this.getFunctionID(a)):FABridge.isASProxy(a)?
(b.type=FABridge.TYPE_ASINSTANCE,b.value=a.fb_instance_id):(b.type=FABridge.TYPE_ANONYMOUS,b.value=a);return b},deserialize:function(a){var b,c=typeof a;if("number"==c||"string"==c||"boolean"==c||null==a||void 0==a)b=this.handleError(a);else if(FABridge.isArray(a)){b=[];for(c=0;c<a.length;c++)b[c]=this.deserialize(a[c])}else if("object"==c){for(c=0;c<a.newTypes.length;c++)this.addTypeDataToCache(a.newTypes[c]);for(var e in a.newRefs)this.createProxy(e,a.newRefs[e]);a.type==FABridge.TYPE_PRIMITIVE?
b=a.value:a.type==FABridge.TYPE_ASFUNCTION?b=this.getFunctionProxy(a.value):a.type==FABridge.TYPE_ASINSTANCE?b=this.getProxy(a.value):a.type==FABridge.TYPE_ANONYMOUS&&(b=a.value)}return b},encodeJSON:function(a){var b,c,e,d="";switch(typeof a){case "object":if(a){if(FABridge.isArray(a)){for(c=0;c<a.length;++c)b=this.encodeJSON(a[c]),d&&(d+=","),d+=b;return"["+d+"]"}if("undefined"!=typeof a.toString){for(c in a)b=a[c],"undefined"!=typeof b&&"function"!=typeof b&&(b=this.encodeJSON(b),d&&(d+=","),d+=
this.encodeJSON(c)+":"+b);return"{"+d+"}"}}return"null";case "number":return isFinite(a)?""+a:"null";case "string":e=a.length;d='"';for(c=0;c<e;c+=1)if(b=a.charAt(c)," "<=b){if("\\"==b||'"'==b)d+="\\";d+=b}else switch(b){case "\b":d+="\\b";break;case "\f":d+="\\f";break;case "\n":d+="\\n";break;case "\r":d+="\\r";break;case "\t":d+="\\t";break;default:b=b.charCodeAt(),d+="\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}return d+'"';case "boolean":return""+a;default:return"null"}},addRef:function(a){this.target.incRef(a.fb_instance_id)},
release:function(a){this.target.releaseRef(a.fb_instance_id)},handleError:function(a){if("string"==typeof a&&0==a.indexOf("__FLASHERROR"))throw a=a.split("||"),0<FABridge.refCount&&FABridge.refCount--,Error(a[1]);return a}};ASProxy=function(a,b){this.bridge=a;this.typeName=b;this.className="ASProxy";return this};
ASProxy.prototype={get:function(a){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,a))},set:function(a,b){this.bridge.setPropertyInAS(this.fb_instance_id,a,b)},call:function(a,b){this.bridge.callASMethod(this.fb_instance_id,a,b)},addRef:function(){this.bridge.addRef(this)},release:function(){this.bridge.release(this)}};
var kswfobject=function(){function a(){if(!v){try{var a=h.getElementsByTagName("body")[0].appendChild(h.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}v=!0;for(var a=D.length,c=0;c<a;c++)D[c]()}}function b(a){v?a():D[D.length]=a}function c(a){if(typeof t.addEventListener!=m)t.addEventListener("load",a,!1);else if(typeof h.addEventListener!=m)h.addEventListener("load",a,!1);else if(typeof t.attachEvent!=m)l(t,"onload",a);else if("function"==typeof t.onload){var b=t.onload;t.onload=
function(){b();a()}}else t.onload=a}function e(){var a=h.getElementsByTagName("body")[0],b=h.createElement(y);b.setAttribute("type",E);var c=a.appendChild(b);if(c){var e=0;(function(){if(typeof c.GetVariable!=m){var h=c.GetVariable("$version");h&&(h=h.split(" ")[1].split(","),k.pv=[parseInt(h[0],10),parseInt(h[1],10),parseInt(h[2],10)])}else if(10>e){e++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;d()})()}else d()}function d(){var a=F.length;if(0<a)for(var b=0;b<a;b++){var c=F[b].id,
d=F[b].callbackFn,e={success:!1,id:c};if(0<k.pv[0]){var h=s(c);h&&(H(F[b].swfVersion)&&!(k.wk&&312>k.wk)?(C(c,!0),d&&(e.success=!0,e.ref=g(c),d(e))):(n(h),d&&d(e)))}else if(C(c,!0),d){if((c=g(c))&&typeof c.SetVariable!=m)e.success=!0,e.ref=c;d(e)}}}function g(a){var b=null;if((a=s(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=m?b=a:(a=a.getElementsByTagName(y)[0])&&(b=a);return b}function n(a){if(k.ie&&k.win&&4!=a.readyState){var b=h.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(f(a),
b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(f(a),a)}function f(a){var b=h.createElement("div");if(k.win&&k.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(y)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function u(a){var b=s(a);b&&"OBJECT"==b.nodeName&&(k.ie&&k.win?(b.style.display=
"none",function(){if(4==b.readyState){var c=s(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function s(a){var b=null;try{b=h.getElementById(a)}catch(c){}return b}function l(a,b,c){a.attachEvent(b,c);B[B.length]=[a,b,c]}function H(a){var b=k.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&
b[1]==a[1]&&b[2]>=a[2]?!0:!1}function A(a,b,c,d){if(!k.ie||!k.mac){var e=h.getElementsByTagName("head")[0];if(e){c=c&&"string"==typeof c?c:"screen";d&&(I=p=null);if(!p||I!=c)d=h.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),p=e.appendChild(d),k.ie&&(k.win&&typeof h.styleSheets!=m&&0<h.styleSheets.length)&&(p=h.styleSheets[h.styleSheets.length-1]),I=c;k.ie&&k.win?p&&typeof p.addRule==y&&p.addRule(a,b):p&&typeof h.createTextNode!=m&&p.appendChild(h.createTextNode(a+
" {"+b+"}"))}}}function C(a,b){if(K){var c=b?"visible":"hidden";v&&s(a)?s(a).style.visibility=c:A("#"+a,"visibility:"+c)}}var m="undefined",y="object",E="application/x-shockwave-flash",t=window,h=document,q=navigator,J=!1,D=[function(){J?e():d()}],F=[],G=[],B=[],v=!1,p,I,K=!0,k=function(){var a=typeof h.getElementById!=m&&typeof h.getElementsByTagName!=m&&typeof h.createElement!=m,b=q.userAgent.toLowerCase(),c=q.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),
b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",k=[0,0,0],g=null;if(typeof q.plugins!=m&&typeof q.plugins["Shockwave Flash"]==y){if((g=q.plugins["Shockwave Flash"].description)&&!(typeof q.mimeTypes!=m&&q.mimeTypes[E]&&!q.mimeTypes[E].enabledPlugin))J=!0,e=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),k[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),k[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),k[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0}else if(typeof t.ActiveXObject!=m)try{var f=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(f&&(g=f.GetVariable("$version")))e=!0,g=g.split(" ")[1].split(","),k=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)]}catch(H){}return{w3:a,pv:k,wk:b,ie:e,win:d,mac:c}}();(function(){k.w3&&((typeof h.readyState!=m&&"complete"==h.readyState||typeof h.readyState==m&&(h.getElementsByTagName("body")[0]||h.body))&&a(),v||(typeof h.addEventListener!=m&&h.addEventListener("DOMContentLoaded",
a,!1),k.ie&&k.win&&(h.attachEvent("onreadystatechange",function(){"complete"==h.readyState&&(h.detachEvent("onreadystatechange",arguments.callee),a())}),t==top&&function(){if(!v){try{h.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),k.wk&&function(){v||(/loaded|complete/.test(h.readyState)?a():setTimeout(arguments.callee,0))}(),c(a)))})();(function(){k.ie&&k.win&&window.attachEvent("onunload",function(){for(var a=B.length,b=0;b<a;b++)B[b][0].detachEvent(B[b][1],
B[b][2]);a=G.length;for(b=0;b<a;b++)u(G[b]);for(var c in k)k[c]=null;k=null;for(var d in kswfobject)kswfobject[d]=null;kswfobject=null})})();return{embedSWF:function(a,c,d,e,g,f,l,n,t,A){var u={success:!1,id:c};k.w3&&!(k.wk&&312>k.wk)&&a&&c&&d&&e&&g?(C(c,!1),b(function(){d+="";e+="";var b={};if(t&&typeof t===y)for(var f in t)b[f]=t[f];b.data=a;b.width=d;b.height=e;f={};if(n&&typeof n===y)for(var p in n)f[p]=n[p];if(l&&typeof l===y)for(var q in l)f.flashvars=typeof f.flashvars!=m?f.flashvars+("&"+
q+"="+l[q]):q+"="+l[q];if(H(g)){var v;p=s(c);if(!(k.wk&&312>k.wk)&&p)if(typeof b.id==m&&(b.id=c),k.ie&&k.win){var w="",r;for(r in b)b[r]!=Object.prototype[r]&&("data"==r.toLowerCase()?f.movie=b[r]:"styleclass"==r.toLowerCase()?w+=' class="'+b[r]+'"':"classid"!=r.toLowerCase()&&(w+=" "+r+'="'+b[r]+'"'));r="";for(var x in f)f[x]!=Object.prototype[x]&&(r+='<param name="'+x+'" value="'+f[x]+'" />');p.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+w+">"+r+"</object>";G[G.length]=
b.id;v=s(b.id)}else{x=h.createElement(y);x.setAttribute("type",E);for(var z in b)b[z]!=Object.prototype[z]&&("styleclass"==z.toLowerCase()?x.setAttribute("class",b[z]):"classid"!=z.toLowerCase()&&x.setAttribute(z,b[z]));for(w in f)f[w]!=Object.prototype[w]&&"movie"!=w.toLowerCase()&&(r=x,z=w,v=f[w],q=h.createElement("param"),q.setAttribute("name",z),q.setAttribute("value",v),r.appendChild(q));p.parentNode.replaceChild(x,p);v=x}f=v;b.id==c&&C(c,!0);u.success=!0;u.ref=f}else C(c,!0);A&&A(u)})):A&&A(u)},
ua:k,removeSWF:function(a){k.w3&&u(a)},createCSS:function(a,b,c,d){k.w3&&A(a,b,c,d)},addDomLoadEvent:b,addLoadEvent:c}}();function KongregateAPI(){this.initialize()}
KongregateAPI.prototype={unityElementId:null,initialize:function(){this._flashVarsString="";this._flashVarsObject={};this._services={};this._postMessageParams;this._apiLoadedCallback=null;this._loaded=this._paramsReceived=!1;var a=location.search.split("?")[1];if(a)for(var a=a.split("&"),b=0;b<a.length;b++){var c=a[b].split("=");c&&2==c.length&&this.processParam(c[0],c[1])}if(this._postMessageParams=!this.flashVarsObject().kongregate_ansible_path&&top!=window){var e=this;window.addEventListener("message",
function(a){e.messageOriginIsKongregate(a)&&(a=a.data,"params"==a.type&&e.handleParamsMessage(a.data))});top.postMessage("kongregate_request_params","*")}else this._paramsReceived=!0},processParam:function(a,b){0==a.indexOf("kongregate")&&(this._flashVarsObject[a]=b,this._flashVarsString+=a+"="+b+"&")},flashVarsString:function(){return this._flashVarsString},flashVarsObject:function(){return this._flashVarsObject},getVariable:function(a){return this._flashVarsObject[a]},messageOriginIsKongregate:function(a){var b=
this._flashVarsObject.kongregate_host;return b&&a.origin=="http://"+b||a.origin=="https://"+b},loadAPI:function(a){!this._postMessageParams||this.paramsReceived()?this.doLoadAPI(a):this._apiLoadedCallback=a},handleParamsMessage:function(a){if(!this.paramsReceived()){for(var b in a)this.processParam(b,a[b]);this._paramsReceived=!0;this._apiLoadedCallback&&this.doLoadAPI(this._apiLoadedCallback)}},paramsReceived:function(){return this._paramsReceived},doLoadAPI:function(a){if(this._loaded)"function"===
typeof a&&a();else{var b=this,c=function(){for(var c=FABridge.ansible.root(),d="services stats mtx chat sharedContent analytics".split(" "),g=0;g<d.length;g++){var n=d[g];b._services[n]=c.getServices(n)}b._loaded=!0;"function"==typeof a&&a()};kswfobject.addDomLoadEvent(function(){b.createAnsible(c)})}},getAPI:function(){return this._services},embedFrame:function(a,b){var c=document.getElementById(b?b:"contentdiv"),e;e="<iframe id='content' frameborder='0' style='position:relative;top:0px;left:0px;"+
("border:0px none;padding:0px;width:"+c.offsetWidth+"px;height:"+c.offsetHeight+"px;'");e+="src='"+a+"'></iframe>";c.innerHTML=e},createAnsible:function(a){FABridge.addInitializationCallback("ansible",a);a=document.createElement("div");a.id="ansible_container";a.style.position="absolute";a.style.width=a.style.height="1px";a.style.left=a.style.top="-1000px";document.body.appendChild(a);var b=document.createElement("div");b.id="ansible";a.appendChild(b);a={bridgeName:"ansible",json_encode:"true"};for(var c in this.flashVarsObject())a[c]=
this.flashVarsObject()[c];(c=decodeURIComponent(this.getVariable("kongregate_ansible_path")))&&0!=c.indexOf("http://")&&(c="https:"==location.protocol&&0==c.indexOf("chat.kongregate.com")?"https://"+c.replace("chat.kongregate.com","kongregate1.insnw.net"):"http://"+c);kswfobject.embedSWF(c,"ansible","1","1","9.0.0",null,a,{allowScriptaccess:"always"},null,null)}};kongregateAPI=new KongregateAPI;
"undefined"==typeof kongregateUnitySupport&&(kongregateUnitySupport=function(){function a(a){a=n.getElementById(a);if(!a)return null;var b;l.win&&l.ie?(a=a.getElementsByTagName("object")[0])&&"OBJECT"==a.nodeName&&(b=a):(a=a.getElementsByTagName("embed")[0])&&"EMBED"==a.nodeName&&(b=a);return b&&typeof b.GetPluginVersion==d?null:b}function b(){var b="kongregateUnityDiv";typeof kongregateAPI!=d&&kongregateAPI.unityElementId&&(b=kongregateAPI.unityElementId);return a(b)||a("unityPlayer")}function c(){return[kongregate.services.getUserId(),
kongregate.services.getUsername(),kongregate.services.getGameAuthToken()].join("|")}var e=[],d="undefined",g=navigator,n=document,f=g.userAgent,g=g.platform,u=!1,s=/chrome/i.test(f);/msie/i.test(f)?u=parseFloat(f.replace(/^.*msie ([0-9]+(\.[0-9]+)?).*$/i,"$1")):/Trident/i.test(f)&&(u=parseFloat(f.replace(/^.*rv:([0-9]+(\.[0-9]+)?).*$/i,"$1")));var l={w3:typeof n.getElementById!=d&&typeof n.getElementsByTagName!=d&&typeof n.createElement!=d,win:g?/win/i.test(g):/win/i.test(f),mac:g?/mac/i.test(g):
/mac/i.test(f),ie:u,ff:/firefox/i.test(f),op:/opera/i.test(f),ch:s,ch_v:/chrome/i.test(f)?parseFloat(f.replace(/^.*chrome\/(\d+(\.\d+)?).*$/i,"$1")):!1,sf:/safari/i.test(f)&&!s,wk:/webkit/i.test(f)?parseFloat(f.replace(/^.*webkit\/(\d+(\.\d+)?).*$/i,"$1")):!1,x64:/win64/i.test(f)&&/x64/i.test(f),moz:/mozilla/i.test(f)?parseFloat(f.replace(/^.*mozilla\/([0-9]+(\.[0-9]+)?).*$/i,"$1")):0,mobile:/ipad/i.test(g)||/iphone/i.test(g)||/ipod/i.test(g)||/android/i.test(f)||/windows phone/i.test(f)};l.clientBrand=
l.ch?"ch":l.ff?"ff":l.sf?"sf":l.ie?"ie":l.op?"op":"??";l.clientPlatform=l.win?"win":l.mac?"mac":"???";return{onUnityEmbed:function(a){$("unity_missing")&&(a.success?"missingUnityObject"==a.id?($("missingUnityObject").update(""),$("kongregateUnityDiv").update(""),top.location.replace(decodeURIComponent(kongregateAPI.getVariable("kongregate_game_url")))):$("unity_missing").remove():$("unity_missing").show())},initAPI:function(a,d){e.push({object:a||"KongregateAPI",callback:d||"OnKongregateAPILoaded"});
kongregateAPI.loadAPI(function(){"undefined"===typeof kongregate&&(kongregate=kongregateAPI.getAPI());for(var a=0;a<e.length;a++){var d=e[a];b().SendMessage(d.object,d.callback,c())}e=[]})},getUnityObject:function(){return b()},getUserInfoString:function(){return c()}}}());
